include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    invalid_annotation_target: ignore
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    
linter:
  rules:
    avoid_classes_with_only_static_members: false
    sort_constructors_first: false
    prefer_single_quotes: false
    prefer_double_quotes: false
    unnecessary_this: false

    # Consider activating later on
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    always_specify_types: false
    prefer_final_locals: false
    always_put_required_named_parameters_first: false
    non_constant_identifier_names: false
    sort_unnamed_constructors_first: false
    prefer_constructors_over_static_methods: false
    avoid_unused_constructor_parameters: false
    require_trailing_commas: false
    constant_identifier_names: false
    depend_on_referenced_packages: false
    unnecessary_getters_setters: false

