name: smart_object
description: |
  Exposes capabilities supported by intelligent products to be used by different services. 
  Inspired from OMA IPSO.
publish_to: none

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  dcdg: ^4.0.0
  freezed_annotation: ^0.15.0
  grpc: ^3.0.2
  json_serializable: ^6.0.0
  mockito: ^5.0.16
  protobuf: ^2.0.0
  rxdart: ^0.27.2
  test: ^1.18.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.2
  dart_code_metrics: ^4.4.0
  freezed: ^0.15.0+1
  lint: ^1.7.2
  lints: ^1.0.1
  
dependency_overrides:
  analyzer: ^2.6.0